// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"fmt"
)

// HereMyType1 ...
type HereMyType1 string

// HereMyType2 is appinfo-myType2-appinfo
type HereMyType2 struct {
	LengthAttr *int   `xml:"length,attr"`
	Value      string `xml:",chardata"`
}

// HereMyType3 ...
type HereMyType3 struct {
	LengthAttr *int   `xml:"length,attr"`
	Value      string `xml:",chardata"`
}

// HereMyType4 ...
type HereMyType4 struct {
	Title     string  `xml:"title"`
	Blob      string  `xml:"blob"`
	Timestamp string  `xml:"timestamp"`
	Metadata  *string `xml:"metadata"`
}

// HereMyType5 ...
type HereMyType5 string

// HereMyType6CodeAttr ...
type HereMyType6CodeAttr string

func validateHereMyType6CodeAttr(value string) error {
	switch value {
	case "value1", "value2":
		return nil
	default:
		return fmt.Errorf("HereMyType6CodeAttr must be one of [value1, value2], got %q", value)
	}
}

func (v HereMyType6CodeAttr) Validate() error {
	return validateHereMyType6CodeAttr(string(v))
}

func (v HereMyType6CodeAttr) MarshalText() ([]byte, error) {
	value := string(v)
	if err := validateHereMyType6CodeAttr(value); err != nil {
		return nil, err
	}
	return []byte(value), nil
}

func (v *HereMyType6CodeAttr) UnmarshalText(text []byte) error {
	value := string(text)
	if err := validateHereMyType6CodeAttr(value); err != nil {
		return err
	}
	*v = HereMyType6CodeAttr(value)
	return nil
}

// HereMyType6 ...
type HereMyType6 struct {
	CodeAttr       *HereMyType6CodeAttr `xml:"code,attr,omitempty"`
	IdentifierAttr *int                 `xml:"identifier,attr"`
}

// HereMyType7 ...
type HereMyType7 struct {
	OriginAttr string `xml:"origin,attr"`
	Value      string `xml:",chardata"`
}

// HereMyType8 ...
type HereMyType8 struct {
	Title []*HereMyType4 `xml:"title"`
}

// HereMyType9 ...
type HereMyType9 struct {
	Title []*HereMyType4 `xml:"title"`
}

// HereMyType10 ...
type HereMyType10 struct {
	Title *HereMyType4 `xml:"title"`
}

// HereMyType11 ...
type HereMyType11 struct {
	Option1 *int          `xml:"option1"`
	Option2 *string       `xml:"option2"`
	Option3 *HereMyType10 `xml:"option3"`
}

// HereTopLevel ...
type HereTopLevel struct {
	XMLName         xml.Name       `xml:"TopLevel"`
	CostAttr        *float64       `xml:"cost,attr"`
	LastUpdatedAttr string         `xml:"LastUpdated,attr"`
	Nested          *HereMyType7   `xml:"nested"`
	MyType1         []string       `xml:"myType1"`
	MyType2         []*HereMyType2 `xml:"myType2"`
	*HereMyType6
}
