// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"fmt"
	"strconv"
)

// MemberColor ...
type MemberColor string

func validateMemberColor(value string) error {
	switch value {
	case "red", "green":
		return nil
	default:
		return fmt.Errorf("MemberColor must be one of [red, green], got %q", value)
	}
}

func (v MemberColor) Validate() error {
	return validateMemberColor(string(v))
}

func (v MemberColor) MarshalText() ([]byte, error) {
	value := string(v)
	if err := validateMemberColor(value); err != nil {
		return nil, err
	}
	return []byte(value), nil
}

func (v *MemberColor) UnmarshalText(text []byte) error {
	value := string(text)
	if err := validateMemberColor(value); err != nil {
		return err
	}
	*v = MemberColor(value)
	return nil
}

// MemberUnionValue ...
type MemberUnionValue string

func validateMemberUnionValue(value string) error {
	if _, err := strconv.ParseBool(value); err == nil {
		return nil
	}
	if err := validateMemberColor(value); err == nil {
		return nil
	}
	return fmt.Errorf("MemberUnionValue must match one of [boolean, color], got %q", value)
}

func (v MemberUnionValue) Validate() error {
	return validateMemberUnionValue(string(v))
}

func (v MemberUnionValue) MarshalText() ([]byte, error) {
	value := string(v)
	if err := validateMemberUnionValue(value); err != nil {
		return nil, err
	}
	return []byte(value), nil
}

func (v *MemberUnionValue) UnmarshalText(text []byte) error {
	value := string(text)
	if err := validateMemberUnionValue(value); err != nil {
		return err
	}
	*v = MemberUnionValue(value)
	return nil
}

// MemberValidationTop ...
type MemberValidationTop struct {
	XMLName  xml.Name          `xml:"ValidationTop"`
	AttrAttr *MemberUnionValue `xml:"attr,attr"`
	Value    *MemberUnionValue `xml:"value"`
}
