// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"fmt"
	"strconv"
)

// HereUnionValue ...
type HereUnionValue string

func validateHereUnionValue(value string) error {
	if _, err := strconv.ParseBool(value); err == nil {
		return nil
	}
	if _, err := strconv.ParseInt(value, 10, 0); err == nil {
		return nil
	}
	return fmt.Errorf("HereUnionValue must match one of [boolean, int], got %q", value)
}

func (v HereUnionValue) Validate() error {
	return validateHereUnionValue(string(v))
}

func (v HereUnionValue) MarshalText() ([]byte, error) {
	value := string(v)
	if err := validateHereUnionValue(value); err != nil {
		return nil, err
	}
	return []byte(value), nil
}

func (v *HereUnionValue) UnmarshalText(text []byte) error {
	value := string(text)
	if err := validateHereUnionValue(value); err != nil {
		return err
	}
	*v = HereUnionValue(value)
	return nil
}

// HereUnionTop ...
type HereUnionTop struct {
	XMLName  xml.Name        `xml:"UnionTop"`
	AttrAttr *HereUnionValue `xml:"attr,attr"`
	Value    *HereUnionValue `xml:"value"`
}
